[package]
name = "lzw"
version = "0.4.0"
license = "MIT"
description = "LZW compression and decompression."
authors = ["nwin <nwin@users.noreply.github.com>"]
readme = "README.md"
repository = "https://github.com/nwin/lzw.git"
